apiVersion: batch/v1
kind: Job
metadata:
  name: refresh-database
spec:
  template:
    spec:
      containers:
        - name: refresh-database
          image: minchao/slim-php-realworld-example-app:latest
          command: [ 'sh', '-c', 'composer run refresh-database' ]
          env:
            - name: docker
              value: "true"
            - name: APP_NAME
              value: conduit
            - name: APP_DEBUG
              value: "true"
            - name: APP_LOG_LEVEL
              value: debug
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: $(MYSQL_SERVICE)
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: conduit
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      restartPolicy: Never
