apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: development-
commonLabels:
  variant: development
resources:
  - ../../base
  - job.yaml
  - secret.yaml
patchesStrategicMerge:
  - patch.yaml
patchesJson6902:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: realworld-backend-ingress
      version: v1
    path: patch_backend_ingress.yaml
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: realworld-frontend-ingress
      version: v1
    path: patch_frontend_ingress.yaml

vars:
  - name: MYSQL_SERVICE
    objref:
      kind: Service
      name: mysql
      apiVersion: v1
