apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: minchao/slim-php-realworld-example-app:1.0.0
          env:
            - name: docker
              value: "true"
            - name: APP_NAME
              value: conduit
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: http://dev.realworld.local
            - name: APP_LOG_LEVEL
              value: debug
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: $(MYSQL_SERVICE)
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: conduit
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-pass
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: jwt-secret
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: minchao/vue3-realworld-example-app:1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
