apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-gitops/argo-cd/overlays/development
    repoURL: https://github.com/minchao/cd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
