apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-gitops/argo-rollouts/base
    repoURL: https://github.com/minchao/cd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
