apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realworld-example-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: realworld-example-app/overlays/development
    repoURL: https://github.com/minchao/cd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
