apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  labels:
    app: frontend-preview
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: frontend
