apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/install.yaml
namespace: argo-rollouts
