resources:
  - wordpress
  - mysql
namePrefix: demo-
patchesStrategicMerge:
  - patch.yaml
patchesJson6902:
  - target:
      kind: Service
      name: wordpress
      version: v1
    path: patch_service.yaml

vars:
  - name: WORDPRESS_SERVICE
    objref:
      kind: Service
      name: wordpress
      apiVersion: v1
  - name: MYSQL_SERVICE
    objref:
      kind: Service
      name: mysql
      apiVersion: v1
