apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend
  - ./frontend
  - ./mysql
  - ingress.yaml
configurations:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/docs/features/kustomize/rollout-transform.yaml
