apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: development-
commonLabels:
  variant: development
resources:
  - ./development/argo-cd.yaml
  - ./development/argo-rollouts.yaml
  - ./development/realworld-example-app.yaml
namespace: argocd
